const quizData = [
    { question: 'Who is considered the father of computer science?', options: ['Alan Turing', 'Bill Gates', 'Charles Babbage'], answer: 0 },
    { question: 'Who developed the first compiler for a programming language?', options: ['Ada Lovelace', 'Grace Hopper', 'Linus Torvalds'], answer: 1 },
    { question: 'Who invented the World Wide Web?', options: ['Tim Berners-Lee', 'Steve Jobs', 'Mark Zuckerberg'], answer: 0 },
    { question: 'Who is known as the first computer programmer?', options: ['Ada Lovelace', 'Alan Turing', 'John von Neumann'], answer: 0 },
    { question: 'Who co-founded Microsoft?', options: ['Steve Wozniak', 'Paul Allen', 'Linus Torvalds'], answer: 1 },
    { question: 'Who created the C programming language?', options: ['Dennis Ritchie', 'Bjarne Stroustrup', 'James Gosling'], answer: 0 },
    { question: 'Who developed the Linux operating system?', options: ['Linus Torvalds', 'Richard Stallman', 'Ken Thompson'], answer: 0 },
    { question: 'Who is the creator of Python programming language?', options: ['Guido van Rossum', 'James Gosling', 'Donald Knuth'], answer: 0 },
    { question: 'Who invented Java programming language?', options: ['James Gosling', 'Brendan Eich', 'Guido van Rossum'], answer: 0 },
    { question: 'Who developed the first mechanical computer?', options: ['Charles Babbage', 'Alan Turing', 'John McCarthy'], answer: 0 },
    { question: 'Who invented the term \"Artificial Intelligence\"?', options: ['John McCarthy', 'Marvin Minsky', 'Alan Turing'], answer: 0 },
    { question: 'Who is known for developing the Unix operating system?', options: ['Ken Thompson', 'Dennis Ritchie', 'Linus Torvalds'], answer: 0 },
    { question: 'Who co-founded Apple Inc. with Steve Jobs?', options: ['Bill Gates', 'Steve Wozniak', 'Paul Allen'], answer: 1 },
    { question: 'Who invented the first computer mouse?', options: ['Douglas Engelbart', 'Bill Gates', 'Tim Berners-Lee'], answer: 0 },
    { question: 'Who created the concept of a neural network?', options: ['Donald Hebb', 'Geoffrey Hinton', 'Alan Turing'], answer: 0 },
    { question: 'Who wrote \"The Art of Computer Programming\"?', options: ['Donald Knuth', 'Alan Turing', 'Edsger Dijkstra'], answer: 0 },
    { question: 'Who created the first digital programmable computer?', options: ['Konrad Zuse', 'Charles Babbage', 'John von Neumann'], answer: 0 },
    { question: 'Who is known for the Turing Test?', options: ['Alan Turing', 'John von Neumann', 'Claude Shannon'], answer: 0 },
    { question: 'Who is the father of information theory?', options: ['Claude Shannon', 'Alan Turing', 'John McCarthy'], answer: 0 },
    { question: 'Who invented Fortran?', options: ['John Backus', 'Dennis Ritchie', 'Ken Thompson'], answer: 0 },
    { question: 'Who is the creator of JavaScript?', options: ['Brendan Eich', 'James Gosling', 'Linus Torvalds'], answer: 0 },
    { question: 'Who created Ruby programming language?', options: ['Yukihiro Matsumoto', 'Guido van Rossum', 'James Gosling'], answer: 0 },
    { question: 'Who co-created the TCP/IP protocols?', options: ['Vint Cerf', 'Tim Berners-Lee', 'Linus Torvalds'], answer: 0 },
    { question: 'Who is the founder of Wikipedia?', options: ['Jimmy Wales', 'Larry Page', 'Sergey Brin'], answer: 0 },
    { question: 'Who created Git?', options: ['Linus Torvalds', 'Richard Stallman', 'Guido van Rossum'], answer: 0 },
    { question: 'Who invented the concept of Hypertext?', options: ['Ted Nelson', 'Tim Berners-Lee', 'Douglas Engelbart'], answer: 0 },
    { question: 'Who is known for the algorithm Dijkstra\'s algorithm?', options: ['Edsger Dijkstra', 'Donald Knuth', 'John von Neumann'], answer: 0 },
    { question: 'Who created the first modern relational database system?', options: ['Edgar F. Codd', 'Donald Knuth', 'Charles Babbage'], answer: 0 },
    { question: 'Who developed the BASIC programming language?', options: ['John Kemeny & Thomas Kurtz', 'Dennis Ritchie', 'Ken Thompson'], answer: 0 },
    { question: 'Who is considered the father of modern AI?', options: ['Marvin Minsky', 'John McCarthy', 'Alan Turing'], answer: 1 }
];
