const quizData = [
    { question: 'Who invented SSH (Secure Shell)?', options: ['Linus Torvalds', 'Tim Berners-Lee', 'Tatu Ylönen'], answer: 2 },
    { question: 'What was the first high-level programming language?', options: ['C', 'Fortran', 'COBOL'], answer: 1 },
    { question: 'When was the first neural network programmed?', options: ['1958', '1965', '1975'], answer: 0 },
    { question: 'Who developed the concept of the first algorithm?', options: ['Ada Lovelace', 'Alan Turing', 'John von Neumann'], answer: 0 },
    { question: 'When was the first computer virus created?', options: ['1983', '1986', '1990'], answer: 1 },
    { question: 'Who proposed the concept of the stored-program computer?', options: ['John von Neumann', 'Alan Turing', 'Claude Shannon'], answer: 0 },
    { question: 'Which was the first general-purpose electronic computer?', options: ['ENIAC', 'UNIVAC', 'IBM 701'], answer: 0 },
    { question: 'Who developed the first search engine?', options: ['Larry Page', 'Alan Emtage', 'Tim Berners-Lee'], answer: 1 },
    { question: 'In what year was the World Wide Web invented?', options: ['1989', '1991', '1995'], answer: 0 },
    { question: 'Who is known as the father of information theory?', options: ['Claude Shannon', 'Alan Turing', 'John McCarthy'], answer: 0 },
    { question: 'What was the first graphical web browser?', options: ['Mosaic', 'Netscape', 'Internet Explorer'], answer: 0 },
    { question: 'When was the first iPhone released?', options: ['2005', '2007', '2010'], answer: 1 },
    { question: 'Which computer was the first to run a stored program?', options: ['ENIAC', 'EDSAC', 'UNIVAC'], answer: 1 },
    { question: 'Who invented public-key cryptography?', options: ['Whitfield Diffie & Martin Hellman', 'Ron Rivest', 'Alan Turing'], answer: 0 },
    { question: 'When was ARPANET launched?', options: ['1965', '1969', '1972'], answer: 1 },
    { question: 'Who coined the term \"debugging\"?', options: ['Grace Hopper', 'Ada Lovelace', 'Charles Babbage'], answer: 0 },
    { question: 'Which programming language was used to write UNIX?', options: ['C', 'Assembly', 'Pascal'], answer: 0 },
    { question: 'When was the first email sent?', options: ['1965', '1971', '1975'], answer: 1 },
    { question: 'What was the first computer game?', options: ['Pong', 'Spacewar!', 'Tetris'], answer: 1 },
    { question: 'Which company developed the first hard disk drive?', options: ['IBM', 'Seagate', 'Western Digital'], answer: 0 },
    { question: 'Who is credited with the invention of blockchain?', options: ['Satoshi Nakamoto', 'Vitalik Buterin', 'Hal Finney'], answer: 0 },
    { question: 'When was the first laptop computer released?', options: ['1981', '1985', '1990'], answer: 0 },
    { question: 'Who created the Linux kernel?', options: ['Richard Stallman', 'Linus Torvalds', 'Ken Thompson'], answer: 1 },
    { question: 'What was the first commercial computer?', options: ['ENIAC', 'UNIVAC I', 'IBM 701'], answer: 1 },
    { question: 'Who founded the Free Software Foundation?', options: ['Richard Stallman', 'Linus Torvalds', 'Donald Knuth'], answer: 0 },
    { question: 'Which company created the first computer mouse?', options: ['Apple', 'Xerox', 'IBM'], answer: 1 },
    { question: 'What was the first widely-used search engine?', options: ['Google', 'AltaVista', 'Yahoo!'], answer: 1 },
    { question: 'When was JavaScript created?', options: ['1993', '1995', '1998'], answer: 1 },
    { question: 'Who created the term \"cyberspace\"?', options: ['William Gibson', 'Neal Stephenson', 'Douglas Adams'], answer: 0 },
    { question: 'When was the first computer worm released?', options: ['1988', '1991', '1995'], answer: 0 }
];
